### ISSUE TITLE
How to get the diffusion cache? It seems like the link of hugging face is invalid.

### ISSUE THREAD

**Issue by yxWu777** [autonomousvision/sledge#8]
Hi Authors,
Thanks for this really cool work. I have finished the step of training autoencoder and latent caching. But I have a problem while training the diffusion model. I meet the error: "ValueError: The repository for rvae_latent_dataset contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/rvae_latent_dataset." And the hugging face link is invalid.

**Comment by yxWu777** [comment]
The complete error is shown below.
`2024-10-15 15:58:23,790 INFO {/mnt/lpai-dione/ssai/cvg/team/didonglin/wyx/SLEDGE/sledge/script/builders/diffusion_builder.py:84}  Building Dataset...
The repository for rvae_latent_dataset contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/rvae_latent_dataset.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] Error executing job with overrides: ['py_func=training', 'seed=0', 'job_name=training_dit_diffusion', '+diffusion=training_dit_model', 'diffusion_model=dit_b_model', 'cache.autoencoder_cache_path=/mnt/lpai-dione/ssai/cvg/team/didonglin/wyx/SLEDGE/exp/caches/autoencoder_cache', 'cache.cleanup_diffusion_cache=False', 'autoencoder_checkpoint=/mnt/lpai-dione/ssai/cvg/team/didonglin/wyx/SLEDGE/exp/exp/training_rvae_model/training_rvae_model/2024.10.13.13.38.06/best_model/epoch\\=49-step\\=49.ckpt', 'diffusion_checkpoint=null']
Traceback (most recent call last):
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/datasets/load.py", line 120, in resolve_trust_remote_code
    answer = input(
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/datasets/load.py", line 102, in _raise_timeout_error
    raise ValueError(
ValueError: Loading this dataset requires you to execute custom code contained in the dataset repository on your local machine. Please set the option `trust_remote_code=True` to permit loading of this dataset.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lpai-dione/ssai/cvg/team/didonglin/wyx/SLEDGE/sledge/script/run_diffusion.py", line 63, in <module>
    main()
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/mnt/lpai-dione/ssai/cvg/team/didonglin/wyx/SLEDGE/sledge/script/run_diffusion.py", line 55, in main
    run_training_diffusion(cfg)
  File "/mnt/lpai-dione/ssai/cvg/team/didonglin/wyx/SLEDGE/sledge/diffusion/experiments/training.py", line 63, in run_training_diffusion
    dataset = build_dataset(cfg)
  File "/mnt/lpai-dione/ssai/cvg/team/didonglin/wyx/SLEDGE/sledge/script/builders/diffusion_builder.py", line 91, in build_dataset
    dataset = load_dataset(
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/datasets/load.py", line 2594, in load_dataset
    builder_instance = load_dataset_builder(
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/datasets/load.py", line 2266, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/datasets/load.py", line 1809, in dataset_module_factory
    return LocalDatasetModuleFactoryWithScript(
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/datasets/load.py", line 962, in get_module
    trust_remote_code = resolve_trust_remote_code(self.trust_remote_code, self.name)
  File "/mnt/pfs-mc0p4k/ssai/cvg/team/envs/sledge/lib/python3.9/site-packages/datasets/load.py", line 133, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for rvae_latent_dataset contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/rvae_latent_dataset`

**Comment by DanielDauner** [comment]
Hi @yxWu777 

Unfortunately, I cannot reproduce the issue. We did not upload a dataset to hugging face and in theory the hugging face dataset format should only utilize the code local in the repository. Have you made any changes to the code? Did you enter `y` when asked `Do you wish to run the custom code? [y/N]`?

You can inspect the local dataset code [here](https://github.com/autonomousvision/sledge/blob/main/sledge/diffusion/dataset/rvae_latent_dataset.py).

Best
Daniel

**Comment by DanielDauner** [comment]
Hi @yxWu777

My colleague @raniatze made me aware that the `BUILDER_CONFIG_CLASS` needs to be added in the hugging face dataset. Could you test whether the issue remains?

**Comment by yxWu777** [comment]
Hi @DanielDauner 
Thanks for your help, but the error still exists.

**Comment by DanielDauner** [comment]
Hi @yxWu777

Could you check again with the new commit?

**Comment by yxWu777** [comment]
Hi @DanielDauner 
The code is working. Thanks for your reminder and your efforts in maintaining the code.

**Comment by DanielDauner** [comment]
Happy to hear. All thanks goes to @raniatze!
